# config.yaml - Configuration file for Mona LLM

model:
  name: Mona_LLM
  layers: 12                 # Number of transformer layers
  hidden_size: 768           # Size of hidden layer in each transformer block
  attention_heads: 12        # Number of attention heads
  vocab_size: 30522          # Size of the vocabulary

training:
  epochs: 10                 # Number of training epochs
  batch_size: 32             # Training batch size
  learning_rate: 0.001       # Learning rate for optimizer
  optimizer: AdamW           # Optimizer type

archetypes:
  - name: Sage
    description: "Offers wisdom and cryptic insights."
  - name: Trickster
    description: "Playful and unpredictable."
  - name: Dreamer
    description: "Imaginative and hopeful."
  - name: Visionary
    description: "Forward-thinking and aspirational."

# Miscellaneous settings
output_dir: "output/"         # Directory to save model outputs
log_level: "INFO"             # Logging level (e.g., INFO, DEBUG)
